<?php
/**
 * @category    Development
 * @package     Vinay_Newsletterguru
 * @version     1.0.0
 * @copyright   Copyright (c) 2015 
 * @author	Vinay verma
 * @devleoper   vinayverma.march1991@gmail.com
 * Address      Rocking India

 */
 if($this->getEnablesnow()){ ?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'/newsletterguru/snow-plugin.js'; ?>"></script>

<?php    $fl =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'newsletterguru/images/snow.png'; ?>
<?php } ?>
<style>
.snow-canvas {
	display: block;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
	position: fixed;
	pointer-events: none;
}
</style>
	<?php
	if ($this->isActivePopUp()):
	$collection = Mage::getModel('newsletterguru/newsletterguru')->getCollection()->addFieldToFilter('newsletterguru_id',$this->getTheme());
	foreach($collection->getData() as $col)
	{
	$Template_html = $col['content'];
	$thmem  = $col['title'];
	}
	?>
	<?php if($thmem!='default'){ ?>
	<style>
		#mgnlg_box_layer {
		background: rgba(255, 255, 255, 0.54) none repeat scroll 0 0;
		border-radius: 12px;
		box-shadow: 3px 0 11px -3px rgba(0, 0, 0, 0.75);
	}
	</style>
	<?php } ?>
<script type="text/javascript">
             val = '<?php echo Mage::getStoreConfig('newsletter/general/cookielifetime'); ?>';
                
</script>
<div id="mgnlg_background_layer">
    <div id="mgnlg_box_layer">
        <div id="mgnlg_box_close"></div>
        <?php if ($Template_html): ?>  
        <div id="mgnlg_box_block_3">
            <?php echo $Template_html; ?>
        </div>
        <?php endif; ?>
        <div class="mgnlg_box_lines"></div>
        <div id="mgnlg_box_subscribe">
            <div id="mgnlg_box_subscribe_response_error"></div>
            <div id="mgnlg_box_subscribe_response_success"></div>
            <div id="mgnlg_box_subscribe_form">
                <div id="mgnlg_box_subscribe_input"><input onclick="if(this.value=='<?php echo $this->__('Email'); ?>') this.value=''" onblur="if(this.value=='') this.value='<?php echo $this->__('Email'); ?>'" id="mgnlg_email" name="subscribe_email" value="<?php echo $this->__('Email'); ?>" type="text"></div>
                <div id="mgnlg_box_subscribe_submit"><a href="javascript:void(0)" id="mgnlg_submit" ><?php echo $this->__('Subscribe'); ?></a></div>
            </div>
        </div>
<?php if($this->getEnablesnow()){ ?>
     <canvas class="snow-canvas" speed="1" interaction="false" size="2" count="80" opacity="0.00001" start-color="rgba(253,252,251,1)" end-color="rgba(251,252,253,0.3)" wind-power="0" image="false" width="1366" height="667"></canvas>
    <canvas class="snow-canvas" speed="3" interaction="true" size="6" count="30" start-color="rgba(253,252,251,1)" end-color="rgba(251,252,253,0.3)" opacity="0.00001" wind-power="2" image="false" width="1366" height="667"></canvas>


    <canvas class="snow-canvas" speed="3" interaction="true" size="12" count="20" wind-power="-5" image="<?php echo $fl ?>" width="1366" height="667"></canvas>
<canvas class="snow-canvas" speed="3" interaction="true" size="12" count="20" wind-power="-5" image="<?php echo $fl ?>" width="1366" height="667"></canvas>

<script >
$j = jQuery.noConflict();
$j( document ).ready(function() {
   $j(".snow-canvas").snow();
});


</script>
<?php } ?>
    </div>  
</div>
<?php endif; ?>
